### ISSUE TITLE
Error reading "config.json" - Unhandled rejection Error: Module parse failed

### ISSUE THREAD

**Issue by jadhavajay** [Vheissu/Aurelia-Configuration#63]
I am using webpack. I followed the steps given in "Getting Started" section in Readme.
However, I am getting following error while loading the "config.json" itself.
```
Unhandled rejection Error: Module parse failed: C:\myproject\src\config\config.json Unexpected token (2:6)
You may need an appropriate loader to handle this file type.
| {
| 	"api": {
| 		"baseUrl": "http://localhost:8080/"
| 	}
    at Object.261 (http://localhost:9000/app.bundle.js:28649:7)
    at __webpack_require__ (http://localhost:9000/aurelia-bootstrap.bundle.js:57:38)
    at webpackContext (http://localhost:9000/app.bundle.js:28406:9)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15642:48
From previous event:
    at Promise.then._this2.modulesBeingLoaded.(anonymous function) (http://localhost:9000/aurelia-bootstrap.bundle.js:15641:99)
From previous event:
    at WebpackLoader._import (http://localhost:9000/aurelia-bootstrap.bundle.js:15629:18)
    at WebpackLoader.loadText (http://localhost:9000/aurelia-bootstrap.bundle.js:15695:17)
    at Configure.loadConfigFile (http://localhost:9000/app.bundle.js:11425:28)
    at Configure.loadConfig (http://localhost:9000/app.bundle.js:11415:21)
    at http://localhost:9000/app.bundle.js:38239:18
From previous event:
    at Object.configure (http://localhost:9000/app.bundle.js:38238:12)
    at http://localhost:9000/aurelia.bundle.js:14553:34
From previous event:
    at _loadPlugin (http://localhost:9000/aurelia.bundle.js:14551:40)
    at http://localhost:9000/aurelia.bundle.js:14544:14
From previous event:
    at loadPlugin (http://localhost:9000/aurelia.bundle.js:14543:73)
    at next (http://localhost:9000/aurelia.bundle.js:14804:18)
From previous event:
    at next (http://localhost:9000/aurelia.bundle.js:14804:54)
    at http://localhost:9000/aurelia.bundle.js:14811:14
From previous event:
    at FrameworkConfiguration.apply (http://localhost:9000/aurelia.bundle.js:14796:42)
    at Aurelia.start (http://localhost:9000/aurelia.bundle.js:14413:21)
    at Object._callee$ (http://localhost:9000/app.bundle.js:13428:28)
    at tryCatch (http://localhost:9000/aurelia-bootstrap.bundle.js:9271:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://localhost:9000/aurelia-bootstrap.bundle.js:9545:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (http://localhost:9000/aurelia-bootstrap.bundle.js:9304:21)
    at step (http://localhost:9000/app.bundle.js:13467:191)
    at http://localhost:9000/app.bundle.js:13467:451
From previous event:
    at Object.<anonymous> (http://localhost:9000/app.bundle.js:13467:99)
    at Object.configure (http://localhost:9000/app.bundle.js:13443:17)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15454:27
From previous event:
    at config (http://localhost:9000/aurelia-bootstrap.bundle.js:15453:46)
    at handleApp (http://localhost:9000/aurelia-bootstrap.bundle.js:15444:10)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15472:9
From previous event:
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15469:44
From previous event:
    at run (http://localhost:9000/aurelia-bootstrap.bundle.js:15466:24)
    at Object.<anonymous> (http://localhost:9000/aurelia-bootstrap.bundle.js:15491:1)
    at Object.aurelia-bootstrapper-webpack (http://localhost:9000/aurelia-bootstrap.bundle.js:15492:30)
    at __webpack_require__ (http://localhost:9000/aurelia-bootstrap.bundle.js:57:38)
    at Object.259 (http://localhost:9000/aurelia-bootstrap.bundle.js:13363:1)
    at __webpack_require__ (http://localhost:9000/aurelia-bootstrap.bundle.js:57:38)
    at 10 (http://localhost:9000/aurelia-bootstrap.bundle.js:140:18)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:143:10
```

**Comment by Vheissu** [comment]
This should be fixed in the latest 1.0.13. I tested on the Webpack TypeScript skeleton before releasing it.
