### ISSUE TITLE
Crash in DI trying to load 1.0.13

### ISSUE THREAD

**Issue by dkent600** [Vheissu/aurelia-configuration#71]
Honestly, do you test of this plugin?  Sorry for my frustration, but I have yet to obtain a build of this aurelia-configuration that is usable without modification.  So I will be backing out to 1.0.11, again.

With v1.0.13, using system.js to load the module, I get the following exception.  The plugin is unusable as such:

```
Message: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?

Inner Error Stack:
Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
    at Container.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:567:15)
    at Object.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:424:33)
    at InvocationHandler.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:389:168)
    at Container.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:651:25)
    at StrategyResolver.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:130:37)
    at Container.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:582:41)
    at Object.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:418:33)
    at InvocationHandler.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:389:168)
    at Container.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:651:25)
    at StrategyResolver.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:130:37)
    at Container.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:582:41)
    at Object.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:418:33)
    at InvocationHandler.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:389:168)
    at Container.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:651:25)
    at StrategyResolver.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:130:37)
    at Container.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:582:41)
End Inner Error Stack
------------------------------------------------

    at Container.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:567:15)
    at Object.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:424:33)
    at InvocationHandler.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:389:168)
    at Container.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:651:25)
    at StrategyResolver.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:130:37)
    at Container.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:582:41)
    at Object.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:418:33)
    at InvocationHandler.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:389:168)
    at Container.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:651:25)
    at StrategyResolver.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:130:37)
    at Container.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:582:41)
    at Object.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:418:33)
    at InvocationHandler.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:389:168)
    at Container.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:651:25)
    at StrategyResolver.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:130:37)
    at Container.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:582:41)
End Inner Error Stack
------------------------------------------------

    at new AggregateError (http://localhost:51323/jspm_packages/npm/aurelia-pal@1.0.0/aurelia-pal.js:38:13)
    at Container.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:653:15)
    at StrategyResolver.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:130:37)
    at Container.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:582:41)
    at Object.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:418:33)
    at InvocationHandler.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:389:168)
    at Container.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:651:25)
    at StrategyResolver.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:130:37)
    at Container.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:582:41)
    at Object.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:418:33)
    at InvocationHandler.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:389:168)
    at Container.invoke (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:651:25)
    at StrategyResolver.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:130:37)
    at Container.get (http://localhost:51323/jspm_packages/npm/aurelia-dependency-injection@1.0.0/aurelia-dependency-injection.js:582:41)
    at ValueConverterResource.initialize (http://localhost:51323/jspm_packages/npm/aurelia-binding@1.0.6/aurelia-binding.js:4917:33)
    at ResourceDescription.initialize (http://localhost:51323/jspm_packages/npm/aurelia-templating@1.1.1/aurelia-templating.js:2980:21)
```

**Comment by droda59** [comment]
Got a similar prolem with 1.0.13 too. First time I use this plugin, when I inject Configure nothing happens and my VMs don't get loaded. 
Really happy to have found this answer, I installed down to 1.0.11 and it seems to work.

**Comment by dkent600** [comment]
aurelia-configuration  is not getting much attention.

**Comment by droda59** [comment]
Don't understand why though. I setup my site for development and production, based on the current url, and it works great. 
What do people use to call the right endpoints?

**Comment by Vheissu** [comment]
@dkent600 This is open source. I work a full-time day job Monday to Friday, I also have additional work and a 16 month old son, as well as wife. I understand the frustration, but I go through periods of time where I can't devote the required time I need to plugins like this which are free and cost me in time. The reason this plugin is open source is so others can contribute, fixing bugs and making improvements.

The last release was tested in a Webpack skeleton before I put it out. Eventually I will be writing tests for this and sorting out some kind of continuous delivery, but until then, things will be done manually. Unless of course someone wants to work on the tests part.

**Comment by jhsousa** [comment]
Hi, 
Had the same problem, went from 1.0.4 to a the latest and got the dread error ...
Message: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?

Inner Error Stack:
Error: key/value cannot be null or undefined. A
...

What work for me, was importing "Configure" like this 
      import  { Configure } from 'aurelia-configuration';

Removed the curly braces { } and got it working again. Is must be related to the way the class is exported. 

Please try  importing configure as:

     import  Configure  from 'aurelia-configuration';

**Comment by dkent600** [comment]
@jhsousa Thanks for the suggestion.  It doesn't work for me.  I'm using typescript (v2.0.3) and when I try to compile with your suggested change I get the following error message:

> error TS1192: Module ''aurelia-configuration'' has no default export.

You maybe be on to a work-around here, but I'm not enough of a typescript expert to know what it is (other than perhaps to hack at the d.ts)

**Comment by dkent600** [comment]
@jhsousa I should add that if I try to transpile the typescript using the 1.0.13 version of the d.ts I actually get a different error, with or without the suggested work-around:

> error TS2307: Cannot find module 'aurelia-configuration'.

**Comment by Vheissu** [comment]
Try this again now guys. I removed TypeScript compilation and hand-write the typing file. Let me know how this goes.

**Comment by Stephen2** [comment]
You're awesome, thanks @Vheissu, I'll retry this plugin and let you know in coming days

**Comment by dkent600** [comment]
This does not happen for me in the 1.0.14 build, thanks.
