### ISSUE TITLE
plugin is not working with SystemJS loader

### ISSUE THREAD

**Issue by cedrikv** [Vheissu/aurelia-configuration#97]
if you use the cli and choose systemjs as the loader, the plugin doesn't work. 

stacktrace from chrome:
 ```
deep-extend.ts:148:

Unhandled rejection Error: Unexpected token <
  Evaluating http://localhost:9000/aurelia-configuration
  Loading http://localhost:9000/aurelia-configuration
    at eval (<anonymous>)
    at Re (http://localhost:9000/scripts/vendor-bundle.js:3788:25555)
    at http://localhost:9000/scripts/vendor-bundle.js:3788:33164
    at j (http://localhost:9000/scripts/vendor-bundle.js:3788:7565)
    at O (http://localhost:9000/scripts/vendor-bundle.js:3788:7065)
    at k (http://localhost:9000/scripts/vendor-bundle.js:3788:6064)
    at http://localhost:9000/scripts/vendor-bundle.js:3788:39033
From previous event:
    at et.i.import (http://localhost:9000/scripts/vendor-bundle.js:3788:37148)
    at et.import (http://localhost:9000/scripts/vendor-bundle.js:3788:45218)
    at http://localhost:9000/scripts/vendor-bundle.js:11707:29
From previous event:
    at DefaultLoader.loadModule (http://localhost:9000/scripts/vendor-bundle.js:11701:35)
    at _loadPlugin (http://localhost:9000/scripts/vendor-bundle.js:10667:21)
    at http://localhost:9000/scripts/vendor-bundle.js:10660:16
From previous event:
    at loadPlugin (http://localhost:9000/scripts/vendor-bundle.js:10659:75)
    at next (http://localhost:9000/scripts/vendor-bundle.js:10921:20)
From previous event:
    at next (http://localhost:9000/scripts/vendor-bundle.js:10921:56)
    at http://localhost:9000/scripts/vendor-bundle.js:10928:16
From previous event:
    at FrameworkConfiguration.apply (http://localhost:9000/scripts/vendor-bundle.js:10913:44)
    at Aurelia.start (http://localhost:9000/scripts/vendor-bundle.js:10529:39)
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:45:17)
    at http://localhost:9000/scripts/vendor-bundle.js:9430:29
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:9425:56)
    at http://localhost:9000/scripts/vendor-bundle.js:9461:14
From previous event:
    at bootstrap (http://localhost:9000/scripts/vendor-bundle.js:9460:26)
    at http://localhost:9000/scripts/vendor-bundle.js:9447:9
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:9442:61)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:9467:37)
    at i (http://localhost:9000/scripts/vendor-bundle.js:3788:41774)
    at j (http://localhost:9000/scripts/vendor-bundle.js:3788:7565)
    at O (http://localhost:9000/scripts/vendor-bundle.js:3788:7065)
    at k (http://localhost:9000/scripts/vendor-bundle.js:3788:6064)
    at http://localhost:9000/scripts/vendor-bundle.js:3788:39033
    at <anonymous>
```

steps to reproduce
```batch
au new 
 - name test
 - module loader SystemJS (2)
 - Typescript (2)
 - yes
 - yes
cd test
au install aurelia-configuration

add '.plugin('aurelia-configuration')' to main.ts

au run --watch

go to localhost:9000
```
os: ubuntu 16.04
cli: v0.30.1

Using the cli with requirejs as loader works fine.
Using another plugin (like mdl lite) with the cli and systemjs loader works fine.

**Comment by jgillich** [comment]
Not sure if it helps but with Webpack I had to do `.plugin(PLATFORM.moduleName('aurelia-configuration')`

**Comment by diegohb** [comment]
@cedrikv  i'm using cli 0.32.0, windows, and it works with systemjs ... try upgrading cli, they fixed some issues with loader .

**Comment by cedrikv** [comment]
No success, still the same error. The app looks for 'http://localhost:9000/aurelia-configuration', which just returns the bootsrap html:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Aurelia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body aurelia-app="main">
    <script src="scripts/vendor-bundle.js"></script>
    <script>SystemJS.import("aurelia-bootstrapper").catch(function(err) { console.log(err); })</script>
  </body>
</html>

```

**Comment by Vheissu** [comment]
Loading of configuration files and the plugin itself is something being currently streamlined for a next major release.
